#!/bin/bash
#
# prepare the ru-game environment

# create and activate a virtual environment
mkdir venv && virtualenv-2.7 venv
source venv/bin/activate

# install Python dependencies
pip install --upgrade pip
pip install boto3

