#!/bin/bash
#
# Run all tests in the test directory.
#
# If you want to run a single TestCase class from e.g. test_observer.py:
#
#   python -m unittest test_observer.ProcessObserverTest

PYTHONPATH=$(pwd)
python -m unittest discover -s test